import 'package:flutter/widgets.dart';
/// Flutter icons CustomAviahireIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomAviahireIcons
///      fonts:
///       - asset: fonts/CustomAviahireIcons.ttf
///
///
///
class CustomAviahireIcons {
  CustomAviahireIcons._();
  static const _kFontFam = 'CustomAviahireIcons';
  static const _kFontPkg = null;
  static const IconData calendar =
  IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData candidate =
  IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock =
  IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard =
  IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter =
  IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_vert =
  IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group =
  IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link =
  IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list =
  IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData open_menu =
  IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData review =
  IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumb_down =
  IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumb_up =
  IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tick =
  IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time =
  IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user =
  IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData work =
  IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}